---

- include_role:
    name: "microk8s"

- include_role:
    name: "dt-oneagent-classic"
- include_role:
    name: monaco-v2

- set_fact:
    role_path_abs: "{{ role_path }}"

- name: Print all environment variables
  debug:
    var: ansible_env

- include_role:
    name: dt-platform
    tasks_from: ensure-app
  vars:
    dt_app_id: "{{ item }}"
    dt_environment_url_gen3: "{{ extra_vars.dt_environment_url_gen3 }}"
    dt_oauth_sso_endpoint: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    dt_oauth_client_id: "{{ extra_vars.dt_oauth_client_id }}"
    dt_oauth_client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
    dt_oauth_account_urn: "{{ extra_vars.dt_oauth_account_urn }}"
  loop:
    - "dynatrace.redhat.ansible"
    - "dynatrace.ownership"
    - "dynatrace.davis.workflow.actions"
    - "dynatrace.site.reliability.guardian"

- include_role:
    name: monaco-v2
    tasks_from: apply-monaco
  vars:
    monaco_projects_root: "{{role_path_abs}}/files/monaco"  # monaco projects root folder path
    monaco_project: "deploy" # selection of projects or all projects under the root path if set empty
    monaco_manifest_path: "{{role_path_abs}}/files/monaco/manifest.yaml"
    monaco_environment:
      DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3 }}"
      DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
      DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
      DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"

- include_role:
    name: "app-webgoat"
- include_role:
    name: "app-unguard"

- include_role:
    name: app-webgoat
    tasks_from: deploy-ingress
- include_role:
    name: app-webgoat
    tasks_from: source-endpoints
