---
- include_role:
    name: "microk8s"

- include_role:
    name: "dt-oneagent-classic"
- include_role:
    name: monaco-v2

- set_fact:
    role_path_abs: "{{ role_path }}"

- include_role:
    name: monaco-v2
    tasks_from: apply-monaco
  vars:
    monaco_projects_root: "{{role_path_abs}}/files/monaco"  # monaco projects root folder path
    monaco_project: "deploy" # selection of projects or all projects under the root path if set empty
    monaco_manifest_path: ""
- include_role:
    name: "app-webgoat"
- include_role:
    name: "app-unguard"

- include_role:
    name: app-webgoat
    tasks_from: deploy-ingress
- include_role:
    name: app-webgoat
    tasks_from: source-endpoints


# Depoy monaco config from app-unguard (add ownership)
# deploy monaco config custom to this HOT: Workflows, ownership, notebooks?
#- include_role:
#    name: monaco-v2
#    tasks_from: apply-monaco
#  vars:
#    monaco_projects_root: "{{ role_path }}/files/monaco"  # monaco projects root folder path
#    monaco_project: "deploy" # selection of projects or all projects under the root path if set empty
    #monaco_environment:
    #  <ENV_VAR1>: "<env_var1_value>" # for example APP_NAMESPACE: "easytravel" to be used for easytravel to create a dynatrace management zone via monaco
    #  <ENV_VAR2>: "<env_var2_value>" # for example INGRESS_DOMAIN: "easytravel.<HOST_IP>" to detect the application via monaco rules

