---
- include_role:
    name: "microk8s"

- include_role:
    name: "dt-operator-anton"
  vars:
    operator_mode: "applicationMonitoring"

- include_role:
    name: "dt-oneagent-classic"

- include_role:
    name: "app-webgoat"

- include_role:
    name: app-webgoat
    tasks_from: deploy-ingress

- include_role:
    name: app-webgoat
    tasks_from: source-endpoints