- name: Dynatrace - Retrieve Operator bearer token
  shell: "/snap/bin/microk8s.kubectl get secret $(kubectl get sa dynatrace-kubernetes-monitoring -o jsonpath='{.secrets[0].name}' -n {{ dt_operator_namespace }}) -o jsonpath='{.data.token}' -n {{ dt_operator_namespace }} | base64 --decode"
  register: dt_operator_kube_bearer_token_raw
  when: feature_oneagent

- set_fact:
    dt_operator_kube_bearer_token: "{{  dt_operator_kube_bearer_token_raw.stdout }}"
  when: feature_oneagent
