apiVersion: v1
kind: Service
metadata:
  name: webgoat
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: webgoat

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: "{{ .Values.webgoat.image }}"
        imagePullPolicy: "{{ .Values.webgoat.tag }}"
        ports:
        - containerPort: 3000
