---
- name: Install apt packages
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - software-properties-common
    - jq
    - net-tools
    - maven

- name: Download WebGoat jar from GitHub
  become: true
  become_user: root
  get_url:
    #url: https://github.com/WebGoat/WebGoat/releases/download/v2023.4/webgoat-2023.4.jar
    url: https://s3.amazonaws.com/webgoat-war/webgoat-standalone-7.1-SNAPSHOT-exec.jar
    dest: "{{ role_path }}/files/repo/webgoat-2023.4.jar"  # Change this to your desired location

- name: Update apt cache
  become: true
  become_user: root
  apt:
    update_cache: yes

- name: Install OpenJDK 11
  become: true
  become_user: root
  apt:
    name: openjdk-11-jdk
    state: present


#- name: Install OpenJDK 17
#  become: true
#  become_user: root
#  apt:
#    name: openjdk-17-jdk
#    state: present

- name: Run WebGoat
  become: true
  become_user: root
  command:
    cmd: "sudo nohup java -Dfile.encoding=UTF-8 -Dwebgoat.port=8080 -Dwebwolf.port=9090 -Dserver.address=0.0.0.0 -jar {{ role_path }}/files/repo/webgoat-2023.4.jar > /var/log/webgoat.log 2>&1"
    warn: false
