---
- name: Install apt packages
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - software-properties-common
    - jq
    - net-tools
    - maven
    - openjdk-8-jdk
- name: Update apt cache
  become: true
  become_user: root
  apt:
    update_cache: yes



- name: create folder structure
  become: true
  become_user: root
  file:
    path: "{{ role_path }}/files/repo_latest"
    state: directory

- name: Check if WebGoat repository exists
  stat:
    path: "{{ role_path }}/files/repo_latest/WebGoat"
  register: webgoat_repo

- name: Check if WebGoat-Lessons repository exists
  stat:
    path: "{{ role_path }}/files/repo_latest/WebGoat-Lessons"
  register: webgoat_lessons_repo

  
- name: Clone WebGoat repository
  become: true
  become_user: root
  when: not webgoat_repo.stat.exists
  command:
    cmd: 'git clone --branch 7.1 https://github.com/WebGoat/WebGoat.git'
    chdir: "{{ role_path }}/files/repo_latest"
  
- name: Clone WebGoat-Lessons repository
  become: true
  become_user: root
  when: not webgoat_lessons_repo.stat.exists
  command:
    cmd: 'git clone https://github.com/WebGoat/WebGoat-Lessons.git'
    chdir: "{{ role_path }}/files/repo_latest"

- name: make webgoat-lessons repo safe
  become: true
  become_user: root
  command:
    cmd: 'git config --global --add safe.directory /home/ace/ansible/roles/app-webgoat/files/repo_latest/WebGoat-Lessons'
    chdir: '{{ role_path }}/files/repo_latest/WebGoat-Lessons'

- name: make webgoat repo safe
  become: true
  become_user: root
  command:
    cmd: 'git config --global --add safe.directory /home/ace/ansible/roles/app-webgoat/files/repo_latest/WebGoat'
    chdir: '{{ role_path }}/files/repo_latest/WebGoat'

- name: Compiling Lessons
  become: true
  become_user: root
  command:
    cmd: "git checkout develop"
    chdir: "{{ role_path }}/files/repo_latest/WebGoat"

- name: mvn compile webgoat
  become: true
  become_user: root
  shell: |
    git checkout develop && 
    JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 mvn clean compile install
  args:
    executable: /bin/bash
    chdir: "{{ role_path }}/files/repo_latest/WebGoat"

- name: git checkout develop
  become: true
  become_user: root
  command:
    cmd: 'git checkout develop'
    chdir: '{{ role_path }}/files/repo_latest/WebGoat-Lessons'

- name:  mvn package
  become: true
  become_user: root
  command:
    cmd: 'mvn package'
    chdir: '{{ role_path }}/files/repo_latest/WebGoat-Lessons'

- name: Copy lessons over
  become: true
  become_user: root
  command:
    cmd: "cp target/plugins/*.jar ../WebGoat/webgoat-container/src/main/webapp/plugin_lessons/"
    chdir: "{{ role_path }}/files/repo_latest/WebGoat-Lessons"

- name: Execute mvn package in WebGoat directory
  become: true
  become_user: root
  command:
    cmd: 'mvn package'
    chdir: '{{ role_path }}/files/repo_latest/WebGoat'
    

- name: Run WebGoat
  become: true
  become_user: root
  async: 3600  # This will let the task run for 1 hour, adjust as needed
  poll: 0
  command:
    cmd: "sudo java  -Dserver.address=0.0.0.0 -jar webgoat-standalone/target/webgoat-standalone-7.1-exec.jar > /var/log/webgoat.log 2>&1"
    chdir: "{{ role_path }}/files/repo_latest/WebGoat"
    warn: false
