---
- name: Install necessary packages
  become: true
  become_user: root
  apt:
    name:
      - git
      - maven
      - openjdk-8-jdk  # Assuming you want to use Java 11
    state: present

- name: create folder structure
  become: true
  become_user: root
  file:
    path: "{{ role_path }}/files/repo_latest"
    state: directory

- name: Clone WebGoat repository
  become: true
  become_user: root
  command:
    cmd: 'git clone --branch 7.1 https://github.com/WebGoat/WebGoat.git'
    chdir: "{{ role_path }}/files/repo_latest"
  
- name: Clone WebGoat-Lessons repository
  become: true
  become_user: root
  command:
    cmd: 'git clone https://github.com/WebGoat/WebGoat-Lessons.git'
    chdir: "{{ role_path }}/files/repo_latest"
  
- name: Install specific Java version 
  shell: 
    cmd: "./install-java.sh"
    chdir: "{{ role_path }}/files/repo/setup"
  become: true
  become_user: root
