---
- name: Install necessary packages
  become: true
  become_user: root
  apt:
    name:
      - git
      - maven
      - openjdk-11-jdk  # Assuming you want to use Java 11
    state: present

- name: create folder structure
  become: true
  become_user: root
  command:
    cmd: 'mkdir {{ role_path }}/files/repo_latest'
  
- name: Clone WebGoat repository
  become: true
  become_user: root
  command:
    cmd: 'git clone --branch 7.1 https://github.com/WebGoat/WebGoat.git'
    chdir: "{{ role_path }}/files/repo_latest"
  
- name: Clone WebGoat-Lessons repository
  become: true
  become_user: root
  command:
    cmd: 'git clone https://github.com/WebGoat/WebGoat-Lessons.git'
    chdir: "{{ role_path }}/files/repo_latest"
  
- name: Execute mvn package in WebGoat directory
  become: true
  become_user: root
  command:
    cmd: 'mvn package'
    chdir: '{{ role_path }}/files/repo_latest/WebGoat'
    

#- name: Ensure webgoat-standalone-7.1-SNAPSHOT-exec.jarh is executable
#  file:
#    path: "{{ role_path }}/files/repo_latest/WebGoat/webgoat-standalone/target/webgoat-standalone-7.1-exec.jar"
#    mode: '0755'

- name: Run webgoat-standalone jar
  become: true
  become_user: root
  command:
    cmd: "sudo java -Dwebgoat.port=8080 -Dwebwolf.port=9090 -Dserver.address=0.0.0.0 -jar webgoat-standalone-7.1-exec.jar"
    chdir: '{{ role_path }}/files/repo_latest/WebGoat/webgoat-standalone/target'
